language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
  - 11
  - lts/*
  - node

before_script:
  - npm i codecov nyc --save-dev

script:
  - npm run lint
  - npm run coverageTest

after_success: npm run coverage
deploy:
  provider: npm
  email: sdk@moceanapi.com
  api_key:
    secure: ZsQK/OmEFBpGcFMCen1u9gU4DsE8s4Y34vnDbV++z9p2m+0LYydSbE8CIllg6FcRGUJGu7DJ+myQhynmdlPtMg6CybNPVIhBTTCr+wxbruIt7L12a2d57XNOeghEkKNRzMn1e9vh3q9Xeo7GTYeBmQf8ckv2ptMkJXWx8wzUPKctKYJRdHHqV8IyTmY0wg3Nb6DFx4YdxPpFtr1KmreK75VVO4MOQZTEa8Dtcxha9ZhUeE8uqUvoC63rDNmI7chfuE+Vlt0u6h6j6ByOE1kqaBJSv/Klv1C5GgZkhyhCe9anoaS/6/Pv123UczWBvtMrxS4r1iePf0xTN/A3FSy9XiNDBqDV2/9WmOKlk7wBeiiRhwNTH0LstwY8/2TMGBisV68hdAxmzKyR9BX8wXTitOch3dyEKluw0+KOtt5ZqFU3BfYQ2ayrrBrPvEWao7R75TWVHmKISx1Dm2HztL+9SuUv+ccqURdD4jDOOsVGV47WiFwBN25i8Uci1l2zATiM95KTzUC8uRWhQPDQkkyzagyqrXtlWTeJEWgVyAkpVSdSrXmJ/6QokpzlUSn6dplff1fp5Q9TC/k4InottILEeSrA7RcMHKa9h3GUet9Pe9pNP6jyuyHSiPyhEyfZMo5NaykjhSdIPsWoGWUTagE1ibwSY+GOTxX7OEeggDfPvLc=
  on:
    tags: true
    node: node
  skip_cleanup: true
