os:
  - windows
  - linux
  - osx
language: node_js
node_js:
  - 6
  - 8
  - lts/*
  - node

before_script:
  - npm i codecov nyc --save-dev

script:
  - npm run lint
  - npm run coverageTest

after_success: npm run coverage
